# Generated by Django 5.2.4 on 2025-08-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='entite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agents', to='core.entite', verbose_name="Entité d'affectation"),
        ),
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='authentication.agent', verbose_name='Compte Agent associé'),
        ),
    ]
