# Generated by Django 5.2.4 on 2025-07-17 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2025, 7, 17, 3, 40, 28, 378546, tzinfo=datetime.timezone.utc), verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
    ]
