# Generated by Django 5.2.4 on 2025-07-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vehicule_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
